# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

matrix:
  include:
  - os: linux
    env: CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    julia:
      - 0.7
      - 1.0
  - os: osx
    julia:
      - 0.7
      - 1.0

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("GeoRasters")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("GeoRasters")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documentation
  - julia -e 'using Pkg; Pkg.add("Documenter"); using GeoRasters; cd(Pkg.dir("GeoRasters")); include(joinpath("docs", "make.jl"))'
