name = "GeoArrays"
uuid = "2fb1d81b-e6a0-5fc5-82e6-8e06903437ab"
authors = ["Maarten Pronk <git@evetion.nl>"]
version = "0.2.2"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ArchGDAL = "^0.3.0"
CoordinateTransformations = "0.5"
GeoStatsBase = "0.8"
KrigingEstimators = "0.3.4"
RecipesBase = "0.7, 0.8"
StaticArrays = "0.12"
julia = "1"

[extras]
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
KrigingEstimators = "d293930c-a38c-56c5-8ebb-12008647b47a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "KrigingEstimators"]
