name = "GeoArrays"
uuid = "2fb1d81b-e6a0-5fc5-82e6-8e06903437ab"
authors = ["Maarten Pronk <git@evetion.nl>"]
version = "0.3.1"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
KrigingEstimators = "d293930c-a38c-56c5-8ebb-12008647b47a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ArchGDAL = "^0.3.0"
CoordinateTransformations = "0.5, 0.6"
GeoFormatTypes = "0.3"
GeoStatsBase = "0.8.3, 0.9"
RecipesBase = "0.7, 0.8, 1.0"
StaticArrays = "0.12"
julia = "1.3"

[extras]
InverseDistanceWeighting = "6a8e3230-34bb-5a86-b9da-9f7447a06da5"
KrigingEstimators = "d293930c-a38c-56c5-8ebb-12008647b47a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "KrigingEstimators"]
